FROM node:20-alpine

WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем все зависимости (включая dev)
RUN npm ci

# Копируем конфигурационные файлы
COPY tsconfig.json nest-cli.json ./

# Открываем порт
EXPOSE 3002

# Запускаем в dev режиме (код будет монтироваться через volume)
CMD ["npm", "run", "start:dev"]

